version: "3.9"

volumes:
  postgres-server:

services:
#  app:
#      build: .
#      ports:
#        - "8080:8080"
#      depends_on:
#        - "postgres"

  postgres:
    image: 'postgres:latest'
    ports:
      - "5436:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aero-internship
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - postgres-server:/var/lib/postgres-server/data